job('First Maven Project by DSL') {
    description("First maven job generated by DSL ${new Date()}")
    scm {
        github('https://github.com/abrashid/work-sample.git', 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package','maven-samples/single-module/pom.xml')
    }
    publishers {
        // archieve the war file generated
        archiveArtifacts('**/*.jar')
    }
}